name: PHP Build Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1' # Choisis la version de PHP appropriée
          tools: composer

      - name: Install dependencies
        run: composer install

      - name: Run tests
        run: php artisan test # ou `vendor/bin/phpunit` selon ton projet

      # Optionnel : Analyse statique avec PHPStan
      - name: Run PHPStan
        run: vendor/bin/phpstan analyse

      # Optionnel : Vérification des normes de code avec PHP_CodeSniffer
      - name: Run PHP_CodeSniffer
        run: vendor/bin/phpcs --standard=PSR12 app/ # Ajuste le chemin si nécessaire
