name: Production Deployment

on:
  workflow_run:
    workflows: ["Staging Deployment"]  
    types:
      - completed

jobs:
  production_deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1' # Choisis la version de PHP adaptée à ton projet
          tools: composer

      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Run migrations
        run: php artisan migrate --force # ou une commande de migration adaptée à ton projet

      - name: Clear cache
        run: php artisan cache:clear

      - name: Deploy to Production Server
        # env:
        #   SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        #   SERVER_HOST: ${{ secrets.PRODUCTION_SERVER_HOST }}
        #   DEPLOY_PATH: ${{ secrets.PRODUCTION_DEPLOY_PATH }}
        run: |
          echo "Déploiement en cours sur le serveur de production..."
          # Copie les fichiers via rsync ou autre méthode
          # ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY user@$SERVER_HOST "cd $DEPLOY_PATH && git pull origin main && composer install --no-dev --optimize-autoloader && php artisan migrate --force && php artisan cache:clear"
          echo "Déploiement en production réussi !"
