name: Production Deployment

on:
  workflow_run:
    workflows: ["Staging Deployment"]  
    types:
      - completed

jobs:
  production_deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fake Production Deployment
        run: |
          echo "Deploying to Production..."
          # Commande de déploiement fictive
          echo "Deployment to production is successful!"